### ISSUE TITLE
Savoir not in pip anymore?

### ISSUE THREAD

**Issue by jwfu** [DXMarkets/Savoir#3]
I wasn't able to install Savoir using `pip` as it doesn't appear to be in the Pypi repository.
search term: `https://pypi.python.org/pypi?%3Aaction=search&term=Savoir&submit=search`

**Comment by reiven** [comment]
Thanks @jwfu for the advice. Now i've uploaded the package to pypi and you should be able to download the package using pip (https://pypi.python.org/pypi/Savoir)

**Comment by jwfu** [comment]
Download was successful, thanks for fixing!
